# Generated by Django 3.2.9 on 2022-01-07 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='report',
            name='modified',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 3, 47, 6, 201875, tzinfo=utc)),
        ),
    ]
