# Generated by Django 3.2.9 on 2022-01-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(default='Note here'),
        ),
    ]
